name: docker major project image push using gh action 

on:
  push:
    branches:
      - main
jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build ./frontend -t ${{ secrets.DOCKER_HUB_USERNAME }}/major-project-frontend-v1:latest
          docker ./backend -t ${{ secrets.DOCKER_HUB_USERNAME }}/major-project-backend-v1:latest
          docker ./database -t ${{ secrets.DOCKER_HUB_USERNAME }}/major-project-database-v1:latest

      - name: Push images to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/major-project-frontend-v1:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/major-project-backend-v1:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/major-project-database-v1:latest