name: hello from the windows os hello world workflow 
on: 
    workflow_dispatch
jobs:
    say-hello:
        runs-on: windows-latest
        steps:
          - run: echo "Hello from a GitHub Actions workflow!"
    say-bye:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello from the 2nd job in windows workflow"



