name: exlearn needs bloack added
on:
    workflow_dispatch:
#   push:
#     branches:
#       - main
jobs: 
  tf-init:
    runs-on: ubuntu-latest
    steps:
      - run: echo "terraform init in progress"

  tf-validate:
    runs-on: ubuntu-24.04
    needs: 
      - tf-init
    steps:
      - run: echo "terraform validate in sucess after tf-int job"

  tf-plan:
    runs-on: ubuntu-24.04
    needs:
        - tf-init
        - tf-validate
    steps:
      - run: echo "after tf init job and tf validate job i am excuted"