name: this for the bulding pushing image dockerhub

on: 
    workflow_dispatch:
jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build todoapp-docker -t ${{ secrets.DOCKER_HUB_USERNAME }}/multi-stage-docker-build:latest

      - name: Push images to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/multi-stage-docker-build:latest

